[package]
name = "barcode-scanner"
version = "0.1.0"
authors = ["Denys Vitali <denys.vitali@coelis.ch>"]

[dependencies]
serial = "0.4.0"
serde = "1.0"
serde_yaml = "0.7"
futures = "0.1"
hyper = "0.11"
hyper-tls = "0.1"
tokio-core = "0.1"
serde_json = "1.0"